### ISSUE TITLE
Publish to official HL7 registry

### ISSUE THREAD

**Issue by HL7Sverige** [HL7Sweden/basprofiler-r4#49]
https://confluence.hl7.org/pages/viewpage.action?pageId=97454344#FHIRPackageRegistryUserDocumentation-Overview

**Comment by peturv** [comment]
Now that the IG has been published properly, I have added a pull-request to the IG registry containing an entry for the swedish guide: https://github.com/FHIR/ig-registry/pull/179
I'm a bit unsure if there is need to request a review manually or if they will pick it up, but it seems like I can not add assignee or reviewer myself on the PR due to lack of permissions for the repository.

**Comment by vadi2** [comment]
It'll get picked up automatically.
